# Generated by Django 4.1.2 on 2023-02-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("copSite", "0002_remove_copmembership_cop_policy_delete_coppolicy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="copmembership", name="history_of_salvation",
        ),
    ]
